from gymnasium.vector import VectorWrapper
import numpy as np
import copy
from src.utils.rewards import Rewards
from src.utils.rewards import mean_gebv, gebv_std, expected_heterozygosity


class MaxGEBVRewardWrapper(VectorWrapper):
    def __init__(self, env, w_gain=1.0, w_std=0.5, w_inbreed=0.5):
        """
        R = w_gain * G + w_std * σ + w_inbreed * He
        Args:
            w_std: Weight of genetic standard deviation
            w_inbreed: Weight of inbreeding penalty
        """
        super().__init__(env)
        self.w_gain = w_gain
        self.w_std = w_std
        self.w_inbreed = w_inbreed

    def reset(self, **kwargs):
        obs, info = self.env.reset(**kwargs)
        _, metrics = Rewards.mean_gebv_reward(info["GEBV"], obs, self.w_gain, self.w_std, self.w_inbreed)
        info["absolute_GEBV"] = metrics["mean_gebv"].copy()
        info["GEBV_std"] = metrics["gebv_std"].copy()
        info["expected_heterozygosity"] = metrics["he"].copy()
        return obs, info

    def step(self, actions):
        obs, rews, terminated, truncated, info = self.env.step(actions)

        dones = terminated | truncated
        valid_obs = np.array(obs, copy=True)
        if "final_observation" in info and np.any(dones):
            # New initial state generated by the reset-> the true final state
            valid_obs[dones] = np.array(info["final_observation"])[dones]

        # step_rews, metrics = Rewards.mean_gebv_reward(info["GEBV"], valid_obs, self.w_gain, self.w_std, self.w_inbreed)
        current_mean_gebv = mean_gebv(info["GEBV"])
        current_gebv_std = gebv_std(info["GEBV"])
        current_he = expected_heterozygosity(valid_obs)

        new_rews = (self.w_gain * rews) + (self.w_std * current_gebv_std) + (self.w_inbreed * current_he)
        new_rews = np.where(dones, new_rews, 0.0) # only reward when dones else 0

        info["absolute_GEBV"] = current_mean_gebv.copy()
        info["GEBV_std"] = current_gebv_std.copy()
        info["expected_heterozygosity"] = current_he.copy()

        return obs, new_rews, terminated, truncated, info

    def set_attr(self, name, value, indices=None):
        return self.env.set_attr(name, value, indices)
