unique_name: selection_cnn

# Dataset
genome: sample_full_pop_geno.npy
genetic_map: sample_genetic_map.txt
# WandB
project: BreedGym
entity: weilh
disable_wandb: false
# Environment
num_envs: 8
n_eval_envs: 1
individual_per_gen: 200
k_best: 20
n_crosses: 10
num_generations: 10
# Reward
reward_type: "max_gebv"
reward_shaping: false
w_std: 0.5
w_inbreed: 1000.0
# PPO
gamma: 0.92
learning_rate: 1.0e-4
gae_lambda: 0.96
n_epochs: 7
total_timesteps: 500000
n_steps: 1024
batch_size: 64
ent_coeff: 0.0
# CNN
out_channels1: 64
kernel_size1: 32
stride1: 8
out_channels2: 16
kernel_size2: 8
stride2: 2
# Policy
policy_hiddens: 32
value_hiddens: 32
gen_features_dim: 16
# Evaluation during training
eval_freq: 20000
n_eval_episodes: 25
# Paths
log_path: logs
model_path: checkpoints
